name: Build and Deploy GitBook

on:
  push:
    branches:
      - main  # 觸發工作流程的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install GitBook CLI
      run: npm install gitbook-cli -g

    - name: Install GitBook dependencies
      run: gitbook install

    - name: Build GitBook
      run: gitbook build

    - name: Deploy to branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: _book
        publish_branch: gh-pages
